### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by JimmyTron** [SpaceyaTech/mastori-backend#2]
### Blog Posts : 

- [x] Unique Id(PK), 
- [x] Post title 
- [x] Description (small section which highlights the blog post)  
- [x] Content (main content of the post) 
- [x] UserId(FK) 
- [x] Status 
- [x] Date_Created  #7 
- [x] Date_updated  #7 
- [x] #17 
- [x] CategoryID (FK) #6 
- [x] #4 
- [x] #8  #3
- [ ] #14
- [ ] Images Urls(Post can have multiple multimedia files)

**Comment by Msdot001** [comment]
Is anyone working on Number of Views
